### ISSUE TITLE
ExtractLinks running slowly

### ISSUE THREAD

**Issue by greebie** [archivesunleashed/aut#123]
After running unit tests, scripts that use ExtractLinks may be running slower than need be.  The primary reason is that it is using Python libraries instead of the java core.

**Comment by greebie** [comment]
Testing a intermediary fix by changing the for loop to a list comprehension (after reading that comprehensions are faster than maps in most cases).

**Comment by ianmilligan1** [comment]
Continued in #130 (just making it more specific). 😄
