### ISSUE TITLE
Deprecate ExtractGraph

### ISSUE THREAD

**Issue by greebie** [archivesunleashed/aut#174]
We currently do not use the ExtractGraph udf in our documentation and do not take this approach to produce link-structure analysis.  Which raises whether we should add it to the deprecation list.

The JSON output in the class also produces two separate files, which is a downgrade from the WriteGEXF and WriteGraphML functions.

Another option is to revisit the ExtractGraph class to output GEXF or GraphML directly (ie - it does the flatmap etc directly from the RDD).  

Either way, ExtractGraph may be underutilized, so we should consider its future.

**Comment by ianmilligan1** [comment]
For context, it was generated [as part of this hackathon project](https://github.com/archivesunleashed/aut-viz/tree/master/link-vis) and let's you do PageRank calculation right in AUT. 

I think there's still merit to doing the PageRank calculations in AUT.. maybe revisiting it to output GEXF or GraphML directly would be a good approach? What do you think, Ryan?

**Comment by greebie** [comment]
Okay - I think there may be differences in processing speed using ExtractGraph vs flatmapping links as well.  Let's see what I can do.

I'd also like to look at some additional checks (strongly connected components for instance).

**Comment by ianmilligan1** [comment]
Closed but will be moved as part of #179
