### ISSUE TITLE
Major refactoring: io.archivesunleashed.spark -> io.archivesunleashed

### ISSUE THREAD

**Issue by lintool** [archivesunleashed/aut#178]
As part of recent work meeting, I've been assigned to go through the API and revisit all the decision choices in our march toward 1.0.

We should shorten all package names:  `io.archivesunleashed.spark` -> `io.archivesunleashed`

The "spark" package is a holdover from Warcbase when we had support for multiple analysis frameworks (e.g., pig). This is no longer necessary.

**Comment by ianmilligan1** [comment]
👍 sounds good!
