### ISSUE TITLE
Major refactoring: matchbox cleanup

### ISSUE THREAD

**Issue by lintool** [archivesunleashed/aut#179]
Context: As part of a recent work meeting, I've been assigned to go through the API and revisit all the decision choices in our march toward 1.0.

`io.archivesunleashed.matchbox` has a number of classes that doesn't belong. The original intention is for the `matchbox` package to hold UDFs. To be precise, UDFs are things that go inside Spark transformations such as `map` and `flatMap`.

So, for example, `RecordReader` doesn't belong there - it should be moved higher up in the package hierarchy.

A number of other end-to-end Spark pipelines (e.g., `ExtractGraph`) also reside in `matchbox`. These are really "applications" and should be moved to a package called `io.archivesunleashed.app` or something like that.

**Comment by ianmilligan1** [comment]
👍 sounds good!
