### ISSUE TITLE
DataFrame field names: open thread

### ISSUE THREAD

**Issue by lintool** [archivesunleashed/aut#229]
Open thread for discussion: naming conventions for DF fields? Options include:

1. CamelCase: e.g., `SourceUrl`
2. smallCamelCase: e.g., `sourceUrl`
3. Lower-case, underscore-style: e.g., `source_url`

I've been doing (1), but now that I look at the DF queries, I think (3) will "look better". I don't have strong opinions either way, but we should decide on something and make everything consistent.

BTW, the heuristic of "use whatever is the dominant convention in the native language" doesn't help here... because DFs will be natively implemented in Scala, but I assume frequently access in Python.

**Comment by ianmilligan1** [comment]
Let's go with Option 3 then for similarity across projects? (and I think it'll look nice too)
