### ISSUE TITLE
CommandLineAppRunner.scala produces output per WARC instead of combined result.

### ISSUE THREAD

**Issue by greebie** [archivesunleashed/aut#235]
**Describe the bug**
Comes from #225.  Instead of single Gexf file from the RDD[ArchiveRecord] we get one per warc file.  This will not work for our applications in auk etc.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Use the CommandLineAppRunner to produce an output from a directory of warcs.
2. Result will have multiple gexf / txt etc.

**Expected behavior**
A single gexf file produced from the combined directory / rdd.

**Desktop/Laptop (please complete the following information):**
 - OS: [e.g. MacOS 10.13.4]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
The output for gexf also outputs a directory based on the warcfile and then GEXF.xml instead of just filename.graphml or filename.gexf inside an output directory.  This should be changed.

**Suggestion** remove `.foreach()` call from the second `args.input()` call as we usually want to conduct filtering / analysis on the entire rdd.    The output should simply be `filename.graphml` or `filename.gexf` etc.

**Comment by ianmilligan1** [comment]
Confirmed with

```
./spark-2.3.0-bin-hadoop2.7/bin/spark-submit --driver-memory 45G --class io.archivesunleashed.app.CommandLineAppRunner /home/i2millig/aut/aut/target/aut-0.16.1-SNAPSHOT-fatjar.jar --extractor domainGraph --input /mnt/vol1/data_sets/cpp/cpp_warcs_accession_01/partner.archive-it.org/cgi-bin/getarcs.pl/*.gz --output-format GEXF --output /mnt/vol1/derivative_data/test/domain-graph-gexf
```

does generate a big directory of directories with one GEXF each.

I missed this `output-format` test - which it's harder to cat those together than the other derivatives.

**Comment by ianmilligan1** [comment]
Is this a tweak you could implement @TitusAn?

**Comment by TitusAn** [comment]
Yes, I will apply the fix.
