### ISSUE TITLE
Migrate warcbase-resources to aut-resources

### ISSUE THREAD

**Issue by ianmilligan1** [archivesunleashed/aut#30]
We have resources stored over in the [warcbase-resources](https://github.com/lintool/warcbase-resources) repository. We should have it migrated to a new aut-resources repository under the archivesunleashed GitHub organization.

Currently @lintool has admin permission on warcbase-resources.

**Comment by lintool** [comment]
Done! See https://github.com/archivesunleashed/aut-resources
