### ISSUE TITLE
Update Read.me w/ citation information

### ISSUE THREAD

**Issue by SamFritz** [archivesunleashed/aut#497]
Citation information is currently posted only on the [Cloud website](https://cloud.archivesunleashed.org/derivatives). 

Let’s include a section in the AUT read.me that identifies how folks should cite AU tools:

> If you've found the Archives Unleashed Toolkit or Cloud helpful in your research, please consider using the citation below in your publications. Your citations help to further the recognition of using open-source tools for scientific inquiry, assists in growing the web archiving community, and acknowledges the efforts of contributors to this project.
> 
> Archives Unleashed Project. (2019). Archives Unleashed Toolkit (Version 0.50.0). Apache License, Version 2.0.

Happy to implement; posting to confirm if there are any concerns or updates from @ianmilligan1 @ruebot @lintool. E.g. Assumption user will cite version they use in research, or shall we automatically provide citation with most current release noted?  **Archives Unleashed Project. (2020). Archives Unleashed Toolkit (Version 0.80.0). Apache License, Version 2.0.**

We should  also add this info to https://aut.docs.archivesunleashed.org/docs

**Comment by ianmilligan1** [comment]
Good idea!

I would put the most recent version number into the readme, just while we're there. The text looks good, I might just change `please consider using the citation below` to something like `please use some form of the citation below in your publications.` Drops the 'consider' and also notes the multiplicity of citation formats.

**Comment by ianmilligan1** [comment]
Actually, perhaps it would be better if they were encouraged to cite Ruest et al. "The Archives Unleashed Project." I think that's the best canonical citation for the Toolkit, and would help with Google Scholar tracking when we assess impact of publications and the project?

**Comment by ianmilligan1** [comment]
OK, I see a thumbs up from @ruebot here. If you're cool with this too @SamFritz @lintool, do we want to encourage people to cite Ruest et al. as noted in my comment above? Do you want to implement this when you're back in on Monday, @SamFritz?

**Comment by SamFritz** [comment]
Great, thanks all! Will be updating the following areas in the next little bit: 

- [ ] AUT read.me
- [ ] archivesunleashed.org
- [ ] AUT Documentation
- [ ] AUK

with the following citation information:

**Citing Archives Unleashed**

How to cite the Archives Unleashed Toolkit or Cloud in your research:

Nick Ruest, Jimmy Lin, Ian Milligan, and Samantha Fritz. 2020. The Archives Unleashed Project: Technology, Process, and Community to Improve Scholarly Access to Web Archives. In Proceedings of the ACM/IEEE Joint Conference on Digital Libraries in 2020 (JCDL '20). Association for Computing Machinery, New York, NY, USA, 157–166. DOI:https://doi.org/10.1145/3383583.3398513

Your citations help to further the recognition of using open-source tools for scientific inquiry, assists in growing the web archiving community, and acknowledges the efforts of contributors to this project.
